/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DEMO_H_RPCGEN
#define _DEMO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define sandy 0x12345
#define btech 1

#if defined(__STDC__) || defined(__cplusplus)
#define display 1
extern  int * display_1(char **, CLIENT *);
extern  int * display_1_svc(char **, struct svc_req *);
extern int sandy_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define display 1
extern  int * display_1();
extern  int * display_1_svc();
extern int sandy_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DEMO_H_RPCGEN */
